# Generated by Django 4.2.8 on 2023-12-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile_rank_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField()),
                ('project', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('partner', models.CharField(max_length=100)),
                ('wo_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
