# Generated by Django 4.2.8 on 2023-12-17 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_workorder_delete_listitem_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='request_by',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='wo_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='project',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_number',
            field=models.CharField(max_length=100),
        ),
    ]
