# Generated by Django 4.2.8 on 2023-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_workorder_request_by_workorder_wo_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='request_by',
            field=models.CharField(max_length=100),
        ),
    ]
