# Generated by Django 4.2.8 on 2023-12-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_workorder_request_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='project',
            field=models.CharField(max_length=100),
        ),
    ]
