# Generated by Django 4.2.8 on 2023-12-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_workorder_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='wo_date',
            field=models.DateField(),
        ),
    ]
