# Generated by Django 4.2.8 on 2023-12-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_workorder_wo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='request_date',
        ),
    ]
