# Generated by Django 4.2.8 on 2023-12-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_workorder_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='clusterName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='hp',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='qtyA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='qtyB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='remarks',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scopeOfWork',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='siteId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='totalA',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='totalB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='unitPrice',
            field=models.IntegerField(default=0),
        ),
    ]
