# Generated by Django 4.2.8 on 2023-12-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_workorder_clustername_workorder_hp_workorder_qtya_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='clusterName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='hp',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='partner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='project',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='request_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='scopeOfWork',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='siteId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
