# Generated by Django 4.2.8 on 2023-12-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_workorder_clustername_alter_workorder_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
