# Generated by Django 4.2.8 on 2023-12-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_workorder_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='qtyA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='qtyB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='totalA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='totalB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='unitPrice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
