# Generated by Django 4.2.8 on 2023-12-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_workorder_qtya_alter_workorder_qtyb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='qtyA',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='qtyB',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='totalA',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='totalB',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='unitPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
