# Generated by Django 4.2.8 on 2023-12-17 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_workorder_qtya_alter_workorder_qtyb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='qtyA',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='qtyB',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='scopeOfWork',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='totalA',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='totalB',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='unitPrice',
        ),
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scopeOfWork', models.CharField(blank=True, default='', max_length=100)),
                ('qtyA', models.IntegerField(blank=True, default=0, null=True)),
                ('qtyB', models.IntegerField(blank=True, default=0, null=True)),
                ('unitPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('totalA', models.IntegerField(blank=True, default=0, null=True)),
                ('totalB', models.IntegerField(blank=True, default=0, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('workOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes_of_work', to='myapp.workorder')),
            ],
        ),
    ]
