# Generated by Django 4.2.8 on 2023-12-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_workorder_qtya_remove_workorder_qtyb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopeofwork',
            name='workOrder',
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='qtyA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='qtyB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='totalA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='totalB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='unitPrice',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
