# Generated by Django 4.2.8 on 2023-12-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_scopeofwork_workorder_alter_scopeofwork_qtya_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeofwork',
            name='workOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes_of_work', to='myapp.workorder'),
        ),
    ]
