# Generated by Django 4.2.8 on 2023-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_scopeofwork_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeofwork',
            name='qtyA',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='qtyB',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='scopeOfWork',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='totalA',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='totalB',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='unitPrice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
