# Generated by Django 4.2.8 on 2023-12-17 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_scopeofwork_qtya_alter_scopeofwork_qtyb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopeofwork',
            name='qtyA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='qtyB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='remarks',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='scopeOfWork',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='totalA',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='totalB',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='unitPrice',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='scopeofwork',
            name='workOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes_of_work', to='myapp.workorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_date',
            field=models.DateField(blank=True),
        ),
    ]
