# Generated by Django 4.2.8 on 2023-12-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_scopeofwork_qtya_alter_scopeofwork_qtyb_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopeofwork',
            name='workOrder',
        ),
        migrations.AddField(
            model_name='workorder',
            name='workOrder',
            field=models.ManyToManyField(to='myapp.scopeofwork'),
        ),
    ]
