# Generated by Django 4.2.8 on 2023-12-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_scopeofwork_workorder_workorder_workorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scopeofwork',
            old_name='qtyA',
            new_name='qtyActual',
        ),
        migrations.RenameField(
            model_name='scopeofwork',
            old_name='qtyB',
            new_name='qtyBoq',
        ),
        migrations.RenameField(
            model_name='scopeofwork',
            old_name='totalA',
            new_name='totalActual',
        ),
        migrations.RenameField(
            model_name='scopeofwork',
            old_name='totalB',
            new_name='totalBoq',
        ),
    ]
