# Generated by Django 4.2.8 on 2023-12-24 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_userprofile_workorder_ceocheck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deductOrAddition', models.CharField(blank=True, default='', max_length=100)),
                ('deductionTax', models.CharField(blank=True, default='', max_length=100)),
                ('deductionAmount', models.FloatField(blank=True, default=0)),
                ('deductionRemarks', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='workorder',
            old_name='partner',
            new_name='account_name',
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='grandTotalActual',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='grandTotalBoq',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='FACcert',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='NoIssAgr',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='amount',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='bank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='checklist',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='coverAcceptance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='coverOpm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='npwp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='paymentSteps',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='paymentTax',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='paymentTerm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='percentageAmount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='pic',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='shortdate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='taxAmount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='taxPercentage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='taxRemark',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='termAmount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='termPercentage',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='termRemark',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='tl',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='totalAmount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='workType',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='wo_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workOrder',
            field=models.ManyToManyField(to='myapp.deduction'),
        ),
    ]
