# Generated by Django 4.2.8 on 2023-12-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_deduction_rename_partner_workorder_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopeofwork',
            name='grandTotalActual',
        ),
        migrations.RemoveField(
            model_name='scopeofwork',
            name='grandTotalBoq',
        ),
        migrations.AddField(
            model_name='workorder',
            name='deductions',
            field=models.ManyToManyField(to='myapp.deduction'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='finalGrandTotal',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='grandTotalActual',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='grandTotalBoq',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='workOrder',
            field=models.ManyToManyField(to='myapp.scopeofwork'),
        ),
    ]
