# Generated by Django 4.2.8 on 2023-12-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_scopeofwork_grandtotalactual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='percentageAmount',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
