# Generated by Django 4.2.8 on 2023-12-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_workorder_account_name_alter_workorder_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deduction',
            name='deductionTax',
        ),
    ]
