# Generated by Django 4.2.8 on 2023-12-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_deduction_deductiontax'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='deductionCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scopeOfWorkCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
