# Generated by Django 4.2.8 on 2024-01-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_workorder_deductioncount_workorder_scopeofworkcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='workOrder_attachments/'),
        ),
    ]
