# Generated by Django 4.2.8 on 2024-01-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_workorder_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='checklist',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='demo/workOrder_attachments/'),
        ),
    ]
