# Generated by Django 4.2.8 on 2024-01-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_workorder_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='coverAcceptance',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='coverOpm',
        ),
        migrations.AddField(
            model_name='workorder',
            name='checklist_boq_actual_attachment',
            field=models.FileField(blank=True, null=True, upload_to='checklist_boq_actual_attachment/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='cover_acceptance_attachment',
            field=models.FileField(blank=True, null=True, upload_to='cover_acceptance_attachment/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='cover_opm_attachment',
            field=models.FileField(blank=True, null=True, upload_to='cover_opm_attachment/'),
        ),
    ]
