# Generated by Django 4.2.8 on 2024-01-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_workorder_deductions_alter_workorder_workorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='odbId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='suffixId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
