# Generated by Django 4.2.8 on 2024-01-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_workorder_odbid_workorder_suffixid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='FACcert',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='NoIssAgr',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='pic',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='tl',
        ),
        migrations.AddField(
            model_name='workorder',
            name='fac_certificate',
            field=models.FileField(blank=True, null=True, upload_to='fac_certificate/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='no_issue_agreement',
            field=models.FileField(blank=True, null=True, upload_to='no_issue_agreement/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='picture_of_team',
            field=models.FileField(blank=True, null=True, upload_to='picture_of_team/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='team_list',
            field=models.FileField(blank=True, null=True, upload_to='team_list/'),
        ),
    ]
