# Generated by Django 4.2.8 on 2024-01-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_remove_workorder_faccert_remove_workorder_noissagr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='company',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
