# Generated by Django 4.2.8 on 2024-01-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_workorder_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='bak',
            field=models.FileField(blank=True, null=True, upload_to='bak/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='bap_open',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='bap_snd',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='capture_approval',
            field=models.FileField(blank=True, null=True, upload_to='capture_approval/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='capture_drm',
            field=models.FileField(blank=True, null=True, upload_to='capture_drm/'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='form_survey',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='layout',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='remarkD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='surat_izin',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='unitPriceD',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
