# Generated by Django 4.2.8 on 2024-01-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_workorder_bak_workorder_bap_open_workorder_bap_snd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='hpD',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
