# Generated by Django 4.2.8 on 2024-01-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_workorder_hpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='amountD',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
