# Generated by Django 4.2.8 on 2024-01-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_workorder_amountd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(blank=True, default=''),
        ),
    ]
