# Generated by Django 4.2.8 on 2024-01-05 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_workorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
