# Generated by Django 4.2.8 on 2024-01-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_workorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoice/'),
        ),
    ]
