# Generated by Django 4.2.8 on 2024-01-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_workorder_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='scopeofwork',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
