# Generated by Django 4.2.8 on 2024-01-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_workorder_pricing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='remarksOverview',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
