# Generated by Django 4.2.8 on 2024-01-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_workorder_remarksoverview'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='extendable',
            field=models.BooleanField(default=False),
        ),
    ]
