# Generated by Django 4.2.8 on 2024-01-11 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_workorder_extendable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pType', models.CharField(blank=True, default='', max_length=100)),
                ('pPercentage', models.CharField(blank=True, default='', max_length=100)),
                ('pAmount', models.FloatField(blank=True, default=0)),
                ('pStatus', models.CharField(blank=True, default='', max_length=100)),
                ('pDate', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='deduction',
            name='deductOrAddition',
        ),
        migrations.AddField(
            model_name='deduction',
            name='paymentTerm',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='paymentCount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='workorder',
            name='paymentInformation',
            field=models.ManyToManyField(blank=True, to='myapp.payment'),
        ),
    ]
