# Generated by Django 4.2.8 on 2024-01-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_payment_remove_deduction_deductoraddition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deduction',
            old_name='paymentTerm',
            new_name='deductOrAddition',
        ),
    ]
