# Generated by Django 4.2.8 on 2024-01-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_rename_paymentterm_deduction_deductoraddition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='paymentSteps',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='percentageAmount',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='status',
        ),
    ]
