# Generated by Django 4.2.8 on 2024-01-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_remove_workorder_amount_remove_workorder_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pAmount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
