# Generated by Django 4.2.8 on 2024-01-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_alter_payment_pamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='remarks1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workorder',
            name='remarks2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
