# Generated by Django 4.2.8 on 2024-01-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_workorder_remarks1_workorder_remarks2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pAmount',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
