# Generated by Django 4.2.8 on 2024-01-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_alter_payment_pamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='amountD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='hpD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='unitPriceD',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
