# Generated by Django 4.2.8 on 2024-01-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_alter_workorder_amountd_alter_workorder_hpd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='ceoReject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='financeReject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='personalAssistantReject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workorder',
            name='rightHandReject',
            field=models.BooleanField(default=False),
        ),
    ]
