# Generated by Django 4.2.8 on 2024-01-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_workorder_ceoreject_workorder_financereject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='otherCost',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
