# Generated by Django 4.2.8 on 2024-01-19 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_workorder_paymentdate_workorder_proofofpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='paymentDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
