# Generated by Django 4.2.8 on 2024-01-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_alter_workorder_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='paymentDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
