# Generated by Django 4.2.8 on 2024-01-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_alter_workorder_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='proofOfPayment',
            field=models.FileField(blank=True, default=None, null=True, upload_to='proof_of_payment/'),
        ),
    ]
