# Generated by Django 4.2.8 on 2024-01-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_alter_workorder_proofofpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='proofOfPayment',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_payment/'),
        ),
    ]
