# Generated by Django 4.2.8 on 2024-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_alter_workorder_proofofpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='dueDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
